dependencies:
- python=3.8.5
- pip:
  - azure-identity==1.7.0
  - azure-mgmt-datafactory==2.1.0
  - azure-storage-blob==12.9.0
  - azureml-core==1.36.0.post2
  - azureml-pipeline==1.36.0
  - azureml-train-core==1.36.0
  - joblib==1.1.0
  - numpy==1.20.3
  - openpyxl==3.0.9
  - pandas==1.3.4
  - pip==21.2.3
  - pyarrow==3.0.0
  - shap==0.40.0
  - scikit-learn==1.0.1
  - scipy==1.7.3
  - statsmodels==0.13.1